title: Vistas urbanas no Brasil do século XIX
email: palazzo@unb.br
description: >-
  Nas representações pictóricas assim como na crítica de
  arte de finais do século XIX e início do XX, a busca por um cerne
  da cultura nacional no passado imediato desemboca, paradoxalmente, na
  sua teorização como um oco carente de "brasilidade" artística.
baseurl: "/arte_cidade" # the subpath of your site, e.g. /blog
url: "https://dmcpatrimonio.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: p3palazzo
github_username:  dmcpatrimonio

# Build settings
remote_theme: p3palazzo/minima-scholar
plugins:
  - jekyll-feed
  - jekyll-github-metadata
