name: Authorea
on:
  pull_request:
  push:
    branches: [ master ]
  release:
    type: 
    - published
    - edited
    - prereleased
    - released
jobs:
  pandoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Convert from Pandoc-Markdown to LaTeX
      run: make authorea
    - name: Upload LaTeX files
      uses: actions/upload-artifact@v2
      with:
        name: sections
        path: '*.tex'
  build:
    runs-on: ubuntu-latest
    needs: pandoc
    steps:
    - name: Checkout trigger branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Merge changes from master branch
      run: git merge origin/master
    - name: Update LaTeX files
      uses: actions/download-artifact@v2
      with:
        name: sections
        path: ${{ github.workspace }}/
    - name: Checkout CSL styles
      uses: actions/checkout@v2
      with:
        repository: citation-style-language/styles.git
        path: styles
    - name: Test PDF export
      uses: docker://palazzo/pandoc-xnos:2.9.2.1
      with:
        args: "-d spec/varia-pdf.yaml"
    - name: Upload PDF for manual inspection
      uses: actions/upload-artifact@v2
      with:
        name: build-pdf
        path: palazzo-iconografia_urbana.pdf
  authorea:
    env:
      commit_message: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.repository == 'dmcpatrimonio/iconografia_urbana_19'
    steps:
    - name: Checkout authorea branch
      uses: actions/checkout@v2
      with:
        ref : 'authorea'
        fetch-depth: 0
    - name: Update files
      uses: actions/download-artifact@v2
      with:
        name: sections
        path: ${{ github.workspace }}/
    - name: Merge changes from master branch
      run: git merge origin/master
    - name: Commit changes to Authorea branch
      run: |
        cd ${{ github.workspace }}
        git config --local user.email "runner@github.com"
        git config --local user.name  "Automated build"
        git merge origin/master
        git add .
        git commit -m "${{ env.commit_message }}" -a
        git pull
        git push
